[programs.devnet]
crowdfund = "BNFAjhZF1EsQZpcKCGv3tEuc4mDucQtrAVphYQHoNLU"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/crowdfund"]

[toolchain]
anchor_version = "0.32.1"
